# Generated by Django 3.1.2 on 2020-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Titulo', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=30)),
                ('Editorial', models.CharField(max_length=60)),
                ('Numpage', models.IntegerField()),
                ('codigo_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
            ],
        ),
    ]
